default_context:
  project_name: '{{ cookiecutter.project_name }}'
  project_slug: '{{ cookiecutter.project_slug }}'
  domain_main: '{{ cookiecutter.domain_main }}'
  domain_staging: '{{ cookiecutter.domain_staging }}'
  secret_key: '{{ cookiecutter.secret_key }}'
  backend_cors_origins: '{{ cookiecutter.backend_cors_origins }}'
  postgres_password: '{{ cookiecutter.postgres_password }}'
  docker_image_prefix: '{{ cookiecutter.docker_image_prefix }}'
  docker_image_backend: '{{ cookiecutter.docker_image_backend }}'
  docker_image_celeryworker: '{{ cookiecutter.docker_image_celeryworker }}'
  docker_image_frontend: '{{ cookiecutter.docker_image_frontend }}'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
